permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://ogut.github.com
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: ogut
archive: Son Girdiler
assets: /assets
author: Kerem Öğüt
disqus: ~
email: kerem.ogut@bil.omu.edu.tr
facebook: ~
feed: ~
flickr: ~
google: ~
googleanalyticsid: UA-33297379-1
googleplus: ~
gpg: ~
homeurl: http://ogut.github.com
logo: /assets/19/19-normal-128x128.png
organization: ~
picasa: ~
related: Diğer Girdiler
repository: ogut.github.com
ribbon: GitHub'dayım
title: Kerem Öğüt
twitter: ~

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
